apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: create
  name: create-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-deployment
  template:
    metadata:
      labels:
        app: create-deployment
        version: IMAGE_LABEL
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: create-deployment
          image: ghcr.io/punsvikcloud/create-talk:IMAGE_LABEL
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__MyDB
              value: "...TODO..."
---
apiVersion: v1
kind: Service
metadata:
  namespace: create
  name: create-service
spec:
  selector:
    app: create-deployment
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: create
  name: create-ingress
  labels:
    name: create-ingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - create.punsvik.net
      secretName: tls-secret
  rules:
    - host: create.punsvik.net
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: create-service
                port:
                  number: 8080
